BUG_FIX_ISSUES
ThiagoSousaSantana/blackbeard-api pull request #18
Opened 2021-10-08 17:57 UTC by welbertFC

2021-10-19 03:05 UTC, NewtonCesarRoncari requested changes

2021-10-19 03:05 UTC, NewtonCesarRoncari commented on src/main/java/br/com/blackbeard/blackbeardapi/exceptions/ResourceExceptionHandler.java
> +    public ResponseEntity<StandardError<String>> barberArgumentExceptionHandler(
de acordo com a IDE este método não está sendo usado, ou ta sendo por de baixo dos panos de algum framework?

2021-10-19 03:05 UTC, NewtonCesarRoncari commented on src/main/java/br/com/blackbeard/blackbeardapi/exceptions/BarberArgumentException.java
> +    }
este construtor pode ser privado já que sua unica utilização é dentro do próprio arquivo e o outro método é stático

2021-10-19 23:23 UTC, tsantanadev requested changes

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on pom.xml
> -	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Por que foi alterada a identação desse arquivo, teve alguma alteração nele?

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/exceptions/BarberArgumentException.java
> +    public static final String BARBER_NAME_CANNOT_BE_REPEATED = "barber name cannot be repeated";
Mudar mensagem para "There is already a barber with that name for this barbershop"

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/exceptions/BarberArgumentException.java
> +    public static BarberArgumentException barberNameIsNotEquals() {
Mudar nome do metodo para `barberNameAlreadyExists`

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/exceptions/ResourceExceptionHandler.java
> +    public ResponseEntity<StandardError<String>> barberArgumentExceptionHandler(
Ele é usado pelo spring para tratar as BarberArgumentException

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/service/validation/barber/BarberNameIsNotEquals.java
> +        var listBarber = repository.findAllByBarberShopId(barber.getBarberShop().getId());
Não tenho certeza mas acho que se não fizermos o get e set para os atributos de uma Entity o JPA não funciona

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/service/validation/barber/BarberNameIsNotEquals.java
> +public class BarberNameIsNotEquals implements ValidationBarber {
Renomear classe para BarberNameAlreadyExists

2021-10-19 23:23 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/service/validation/barber/ValidationBarber.java
> +public interface ValidationBarber {
Mudar para BarberValidation

2021-10-20 18:44 UTC, welbertFC commented on pom.xml
> -	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Alterei as versões de algumas dependencias do S3, devo ter apertado um ctrl + alt + l, ai indentou

2021-10-21 02:30 UTC, tsantanadev requested changes

2021-10-21 02:30 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/service/BarberService.java
> +        barberValidation.forEach(obj -> obj.validation(barber));
Mudar para `barberValidationList.forEach(validation -> validation.validate(barber));`

2021-10-21 02:30 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/service/BarberService.java
> +        barberValidation.forEach(obj -> obj.validation(barber));
Extrair para um metodo

2021-10-21 02:30 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/repositories/BarberRepository.java
> +    Barber findBarberByBarberShopIdAndName(UUID idBarberShop, String nameBarber);
Retornar Optional

2021-10-21 02:30 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/repositories/BarberRepository.java
> +    Barber findBarberByBarberShopIdAndName(UUID idBarberShop, String nameBarber);
Tentar usar exists

2021-10-21 02:30 UTC, ThiagoSousaSantana commented on src/main/java/br/com/blackbeard/blackbeardapi/service/validation/barber/BarberValidation.java
> +    void validation(Barber barber);
Mudar para `validate`

2021-10-21 02:30 UTC, ThiagoSousaSantana commented on src/test/java/br/com/blackbeard/blackbeardapi/service/BarberServiceTest.java
> +        barberValidation.forEach(v -> {
Ta de sacanagem com esse V?

2021-10-22 23:12 UTC, tsantanadev requested changes

2021-10-22 23:12 UTC, tsantanadev commented on src/main/java/br/com/blackbeard/blackbeardapi/repositories/BarberRepository.java
> +    Boolean existsBarberByNameAndBarberShopId(String nameBarber, UUID idBarberShop);
Mudar para `barberName`

2021-10-22 23:12 UTC, tsantanadev commented on src/main/java/br/com/blackbeard/blackbeardapi/service/BarberService.java
> +    private void callBarberValidation(Barber barber) {
Alterar para `executeBarberValidation`

2021-10-23 20:32 UTC, tsantanadev approved these changes

2021-10-23 20:33 UTC, merged